services:
  mssql:
    # CU13以前とCU14以降で ODBC のパスが異なるので、server:2022-latest ではなく、明示的に指定しておく
    image: mcr.microsoft.com/mssql/server:2022-CU18-ubuntu-22.04
    user: root
    container_name: mssql
    hostname: mssqlhost
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y # エンド ユーザー ライセンス契約を承諾
      - MSSQL_SA_PASSWORD=MyPassword@123 # SAユーザーのパスワード。大文字、小文字、数字、特殊文字のうち3種類を含む8文字以上
      - MSSQL_PID=Developer # ライセンスタイプ. 無料でライセンスが付与される Developer Edition 
      - MSSQL_TCP_PORT=1433
      # - MSSQL_LCID=1041 # 言語ID. 1041=日本語
      - MSSQL_COLLATION=Japanese_CI_AS
      - HOST_NAME=mssqlhost
    volumes: # マッピングを指定
      - ./initdb.d:/docker-initdb.d # 初期化用SQLとSQL Server起動スクリプト
      # - ./log:/var/opt/mssql/log
    # https://qiita.com/75ks/items/b156905968535e23278c
    command: ["/bin/bash", "-c", "/docker-initdb.d/entrypoint.sh"] # SQL Server起動スクリプトを実行

