trigger:
  branches:
    include:
      - develop
      - id/7/pipeline
  paths:
    include:
      - apps/pl-app/*
      - .azure-devops/app-deploy-pipelines.yaml
pool:
  vmImage: ubuntu-latest
steps:
  - task: AzureStaticWebApp@0
    name: DeployStaticWebApp
    displayName: Deploy Static Web App
    inputs:
      app_location: /apps/pl-app
      config_file_location: /apps/pl-app
      output_location: /apps/pl-app/dist
    env:
      azure_static_web_apps_api_token: $(deployment_token)
      HUSKY: 0