trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - apps/pl-app/*
      - .azure-devops/app-deploy-pipelines.yaml
pool:
  vmImage: ubuntu-latest
steps:
  - task: UseNode@1
    inputs:
      version: '20.16.0'
    displayName: 'Install Node.js'
  - task: Npm@1
    inputs:
      command: custom
      customCommand: 'install -g npm@10.8.2'
    displayName: 'Upgrade npm to latest version'
  - task: AzureStaticWebApp@0
    name: DeployStaticWebApp
    displayName: Deploy Static Web App
    inputs:
      app_location: /apps/pl-app
      output_location: /apps/pl-app/dist
    env:
      azure_static_web_apps_api_token: $(deployment_token)