trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - database/*
      - .azure-devops/db-docs-pipeline.yaml
pool:
  vmImage: ubuntu-latest
steps:
- checkout: self
- script: |
    chmod 777 database/initdb.d/entrypoint.sh
  displayName: 'permissions for initdb.d'
- task: DockerCompose@1
  displayName: 'Build and run SQL Server container'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: 'database/docker-compose.yml'
    action: 'Run services'
    detached: true

- script: |
    mkdir jdbc
    wget -P jdbc/ https://download.microsoft.com/download/745da347-bd51-4bf0-a84e-3465608d8856/jpn/sqljdbc_12.10.0.0_jpn.tar.gz
    tar -zxvf jdbc/sqljdbc_12.10.0.0_jpn.tar.gz
  displayName: 'Download JDBC Driver'

- script: |
    mkdir -m 777 output
    ls -R
  displayName: 'Create output directory'

- script: |
    docker pull schemaspy/schemaspy
    docker run \
    -v "$(Build.SourcesDirectory)/output:/output" \
    -v "$(Build.SourcesDirectory)/schemaspy.properties:/schemaspy.properties" \
    -v "$(Build.SourcesDirectory)/sqljdbc_12.10/jpn/jars/:/drivers" \
    --add-host=host.docker.internal:host-gateway \
    schemaspy/schemaspy:latest -connprops encrypt\\=false
  displayName: 'Run SchemaSpy'
- task: PublishPipelineArtifact@1
  displayName: 'Publish SchemaSpy output'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/output'
    artifact: 'SchemaSpy'
    publishLocation: 'pipeline'

- task: DownloadPipelineArtifact@2
  displayName: 'Download SchemaSpy artifact'
  inputs:
    artifact: 'SchemaSpy'
    path: '$(Pipeline.Workspace)/SchemaSpy'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-dev-hobby'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      STORAGE_ACCOUNT_NAME=hibowebstorageaccount
      IP_ADDRESS=$(curl -s https://ipinfo.io/json | jq -r '.ip')
      echo "Your IP address is: $IP_ADDRESS"

      az storage account network-rule add \
        --account-name $STORAGE_ACCOUNT_NAME \
        --ip-address $IP_ADDRESS
      
      sleep 10

      az storage blob upload-batch \
        --account-name $STORAGE_ACCOUNT_NAME \
        --destination '$web' \
        --destination-path 'dbdocs' \
        --source "$(Pipeline.Workspace)/SchemaSpy" \
        --overwrite
