trigger:
  branches:
    include:
      - develop
      - id/8/addpipeline
  paths:
    include:
      - apps/api/*
      - .azure-devops/functions-build-pipeline.yml
pool:
  vmImage: ubuntu-latest
steps:
- task: UseNode@1
  inputs:
    version: '20.15.1'
  displayName: 'Install Node.js'
- task: Npm@1
  inputs:
    command: custom
    customCommand: 'install -g npm@10.8.2'
  displayName: 'Upgrade npm to latest version'
- bash: |
    if [ -f extensions.csproj ]
    then
        dotnet build extensions.csproj --output ./bin
    fi
    npm install 
    npm run build --if-present
    npm prune --production
  workingDirectory: $(System.DefaultWorkingDirectory)/apps/api
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/apps/api"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    artifactName: 'drop'