name: Auto merge
on: push
jobs:
  merge:
    # if: ${{ github.actor == 'dependabot[bot]' }} # dependabot の プルリクエストのみ
    runs-on: ubuntu-latest
    permissions: # マージに必要なパーミッション
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: dependabot/fetch-metadata@v2 # 条件分岐でバッチバージョンかチェック
      - if: ${{ steps.meta.outputs.update-type == 'version-update:semver-patch' }}
        run: |
              # 承認 ※要リポジトリ設定変更。 Setting > Actions > General の GithuActions設定の Allow GitHub Actions create and approve pull にチェック
              gh pr review "${GITHUB_HEAD_REF}" --approve
              # ステータスチェックと自動マージ
              # --merge ... マージコミットを作成してからマージ
              # --auto ... ステータスチェックがすべて成功状態に変わったタイミングで自動的にマージ ※要リポジトリ設定変更。 Setting > Allow auto-merge にチェック
              gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
