name: Auto merge
on: pull_request
jobs:
  merge:
    if: ${{ github.acctor == 'dependabot[bot]' }} # dependabot の プルリクエストのみ
    runs-on: ubuntu-latest
    permissions: # マージに必要なパーミッション
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      # --merge ... マージコミットを作成してからマージ
      # --auto ... ステータスチェックがすべて成功状態に変わったタイミングで自動的にマージ ※要リポジトリ設定変更。 Setting > Allow auto-merge にチェック
      - run: gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
