name: Reusable Workflows
on:
  workflow_call:
    inputs:
      pr-number:
        type: string
        description: 'Pull request number'
        required: false
        default: ${{ github.event.pull_request.number }}
    secrets:
      token:
        required: true
        description: 'GitHub Token'
    outputs:
      message:
        value: ${{ jobs.comment.outputs.pr-comment }} # ワークフローレベルの出力
        description: 'Comment message'
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - id: pr-comment
        run: |
          body="Welocome, ${GITHUB_ACTOR}"
          gh pr comment "${PR_NUMBER}" --body "${body}"
          echo "body=${body}" >> "${GITHUB_OUTPUT}"
        env:
          PR_NUMBER: ${{ inputs.pr-number }}
          GITHUB_TOKEN: ${{ secrets.token }}
    outputs:
      pr-comment: ${{ steps.pr-comment.outputs.body }} # ジョブレベルの出力
